PullListManager/Controllers/ComicIssueController.cs
using CsvHelper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PullListManager.Data;
using PullListManager.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PullListManager.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ComicIssueController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ComicIssueController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult UploadComics()
        {
            ViewData["UploadSuccess"] = "";
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadComics(IFormFile file)
        {
            var books = ReadComicsFromPreviewOrder(file);

            if(!books.Any())
            {
                ViewData["UploadSuccess"] = "You did not upload a Previews Customer Order Form (Text Version)";
                return View();
            }

            if (_context.ComicIssues.Any())
            {
                if (_context.ComicIssues.FirstOrDefault().OrderNumber.Substring(0, 5) == books.FirstOrDefault().OrderNumber.Substring(0, 5))
                {
                    ViewData["UploadSuccess"] = "Comic info has already been submitted";
                    return View();
                }
            }
            

            //Remove all the old comic issues
            _context.RemoveRange(_context.ComicIssues?.ToList());
            await _context.SaveChangesAsync();

            //Add link to each record...
            foreach (var comic in books)
            {
                var orderSlug = string.Concat(comic.OrderNumber.Where(c => !char.IsWhiteSpace(c)));
                comic.PreviewsLink = "https://www.previewsworld.com/Catalog/" + orderSlug;
            }


            //Add the new comic issues
            _context.AddRange(books);
            await _context.SaveChangesAsync();


            ViewData["UploadSuccess"] = "Comic info uploaded from Diamond";
            return View();


        }

        public void SaveComicInfoFromPreviewsOrdeForm(IFormFile filename)
        {
            if (filename == null || filename.Length == 0)
                return;

            var path = Path.Combine(
                Directory.GetCurrentDirectory(), "wwwroot",
                "comics.txt");

            List<string> Allowed = new List<string>() { "FI", "GEM", "SS", "SPOT", "OA", "KIDS", "\t" };
            StreamReader file = new StreamReader(filename.OpenReadStream());
            StreamWriter writeFile = new StreamWriter(path);
            var line = file.ReadLine();
            while (line != "BOOKS")
            {
                line = file.ReadLine();
                foreach (string str in Allowed)
                {
                    if (line.StartsWith(str))
                    {
                        writeFile.WriteLine(line);
                    }
                }
            }

            file.Close();
            writeFile.Close();
        }

        public List<ComicIssue> ReadComicsFromPreviewOrder(IFormFile fileLocation)
        {
            // File doesn't exist...
            if (fileLocation == null || fileLocation.Length == 0)
                return new List<ComicIssue>();

            var path = Path.Combine(
                Directory.GetCurrentDirectory(), "wwwroot",
                "comics.txt");

            List<string> Allowed = new List<string>() { "FI", "GEM", "SS", "SPOT", "OA", "KIDS", "\t" };
            StreamReader file = new StreamReader(fileLocation.OpenReadStream());
            StreamWriter writeFile = new StreamWriter(path);
            var line = file.ReadLine();

            // File is not a Previews Order (Text Version)
            if (line.Substring(0, 8) != "PREVIEWS")
            {
                file.Close();
                writeFile.Close();
                return new List<ComicIssue>();
            }
                

            while (line != "ART BOOKS")
            {
                line = file.ReadLine();
                foreach (string str in Allowed)
                {
                    if (line.StartsWith(str))
                    {
                        writeFile.WriteLine(line);
                    }
                }
            }

            file.Close();
            writeFile.Close();

            StreamReader readFile = new StreamReader(path);
            var csv = new CsvReader(readFile);
            var map = new ComicIssueDTOMap();
            csv.Configuration.RegisterClassMap(map);
            csv.Configuration.Delimiter = "\t";
            csv.Configuration.DetectColumnCountChanges = false;
            csv.Configuration.HasHeaderRecord = false;
            csv.Configuration.MissingFieldFound = null;
            csv.Configuration.BadDataFound = null;

            var records = csv.GetRecords<ComicIssueDTO>();

            var books = new List<ComicIssue>();

            foreach (var r in records)
            {
                books.Add(new ComicIssue(r.OrderNumber, r.Title, r.DeliveryDate, r.SuggestedPrice));
            }

            readFile.Close();
            return books;
        }

    }
}

PullListManager/Controllers/StoreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PullListManager.Data;
using PullListManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PullListManager.Controllers
{
    public class StoreController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public StoreController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        // GET: Store
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Stores.ToListAsync());
        }

        // GET: Store/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser.RoleName == "Owner" && currentUser.StoreId != id)
            {
                // Show "Not Authorized" page
                return RedirectToAction("NotAllowed", "Home");
            }

            var store = await _context.Stores
                .SingleOrDefaultAsync(m => m.Id == id);
            if (store == null)
            {
                return NotFound();
            }

            return View(store);
        }

        // GET: Store/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Store/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,City,State,ZipCode,Website,Phone")] Store store)
        {
            if (ModelState.IsValid)
            {
                _context.Add(store);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(store);
        }

        // GET: Store/Edit/5
        [Authorize(Roles = "Admin, Owner")]
        public async Task<IActionResult> Edit(int? id)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser.RoleName == "Owner" && currentUser.StoreId != id)
            {
                // Show "Not Authorized" page
                return RedirectToAction("NotAllowed", "Home");
            }

            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Stores.SingleOrDefaultAsync(m => m.Id == id);
            if (store == null)
            {
                return NotFound();
            }
            return View(store);
        }

        // POST: Store/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,City,State,ZipCode,Website,Phone")] Store store)
        {
            if (id != store.Id)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser.RoleName == "Owner" && currentUser.StoreId != id)
            {
                // Show "Not Authorized" page
                return RedirectToAction("NotAllowed", "Home");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(store);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StoreExists(store.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = currentUser.StoreId });
            }
            return View(store);
        }

        // GET: Store/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Stores
                .SingleOrDefaultAsync(m => m.Id == id);
            if (store == null)
            {
                return NotFound();
            }

            return View(store);
        }

        // POST: Store/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var store = await _context.Stores.SingleOrDefaultAsync(m => m.Id == id);
            _context.Stores.Remove(store);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Store/PrepOrder
        public async Task<IActionResult> PrepOrder(int id)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser.RoleName == "Owner" && currentUser.StoreId != id)
            {
                // Show "Not Authorized" page
                return RedirectToAction("NotAllowed", "Home");
            }

            var pullLists = await _context.PullLists.Where(p => p.StoreId == id).OrderBy(p => p.CustomerName).ToListAsync();

            if (pullLists.Any())
            {
                return View(pullLists);
            }

            return RedirectToAction(nameof(Index));
        }

        // POST: Store/PrepOrder
        [HttpPost]
        public async Task<IActionResult> PrepOrder(string[] comicIds)
        {
            //var currentUser = await _userManager.GetUserAsync(User);
            //if (currentUser.RoleName == "Owner" && currentUser.StoreId != id)
            //{
            //    // Show "Not Authorized" page
            //    return RedirectToAction("NotAllowed", "Home");
            //}

            var books = new List<ComicBook>();

            foreach(var comicId in comicIds)
            {
                //Split the id string into Comic ID and Pull List Id
                string[] formValues = comicId.Split(':');

                //Create a ComicBook from Comic ID. 
                //Add PullListId to Comic Book.
                var pullListId = Int32.Parse(formValues[1]);
                var issue = await _context.ComicIssues.FindAsync(Guid.Parse(formValues[0]));
                var book = new ComicBook(issue, pullListId);

                //Add it to DB if it's not already there.
                books.Add(book);
            }

            //Check to see if any books have been unchecked. If so, remove them from the database
            //Take the list of all comic books marked as "SELECTED"
            var savedBooks = _context.ComicBooks.Where(c => c.BookStatus == BookStatus.SELECTED);
            //Foreach book in that list, see if they are in the books object by comparing Order Numbers and PullListIds
            foreach(var sBook in savedBooks)
            {
                //If the saved book is in the books object, remove it from the books object
                if (books.Any(b => b.OrderNumber == sBook.OrderNumber && b.PullListId == sBook.PullListId))
                {
                    var bookToRemove = books.SingleOrDefault(b => b.OrderNumber == sBook.OrderNumber && b.PullListId == sBook.PullListId);
                    books.Remove(bookToRemove);
                    
                }
                else //The saved book is NOT in the books object, remove it from the database
                {
                    _context.Remove(sBook);
                }
               
            }

            await _context.AddRangeAsync(books);
            await _context.SaveChangesAsync();
            return RedirectToAction("OrderPrepReport");
        }

        public IActionResult OrderPrepReport()
        {
            List<OrderPrepReportViewModel> orderPrepReportViewModels = new List<OrderPrepReportViewModel>();

            var uniqueIssues = _context.ComicBooks.Where(b => b.BookStatus == BookStatus.SELECTED).GroupBy(b => b.OrderNumber);
            foreach(var issue in uniqueIssues)
            {
                orderPrepReportViewModels.Add(new OrderPrepReportViewModel()
                {
                    ComicIssue = _context.ComicIssues.SingleOrDefault(c => c.OrderNumber == issue.Key),
                    Count = issue.Count(),
                });
            }

            return View(orderPrepReportViewModels);
        }

        private bool StoreExists(int id)
        {
            return _context.Stores.Any(e => e.Id == id);
        }
    }
}

PullListManager/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PullListManager</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/custom.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (SignInManager.IsSignedIn(User))
                {
                    if (User.IsInRole("Admin"))
                    {
                        <a asp-area="" asp-controller="Store" asp-action="Index" class="navbar-brand">PullListManager</a>
                    }
                    else
                    {
                        <a asp-area="" asp-controller="Store" asp-action="Details" asp-route-id="@UserManager.GetUserAsync(User).Result.StoreId" class="navbar-brand">PullListManager</a>
                    }

                }
                else
                {
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">PullListManager</a>
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @*If user is logged in, show the sidebar*@
        @if (SignInManager.IsSignedIn(User))
        {
            @Html.Partial("_Sidenav");
        }

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - PullListManager</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

PullListManager/Views/Shared/_Sidenav.cshtml
<div class="sidenav">
    @if (User.IsInRole("Admin"))
    {
        <a asp-controller="Store" asp-action="Index">Store Accounts</a>
        <a asp-controller="Account" asp-action="Index">User Accounts</a>
        <a asp-controller="ComicIssue" asp-action="UploadComics">Upload Comic Info</a>
    }

</div>