PullListManager/Models/PullList.cs
using System;
using System.Collections.Generic;

namespace PullListManager.Models
{
    public class PullList
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public decimal? DepositAmount { get; set; }
        public DateTime DateCreated { get; set; }
        public ICollection<PullListRequest> PullListRequests { get; set; }
        public bool IsActive { get; set; }
        public string Notes { get; set; }
        public ICollection<ComicBook> Books { get; set; }
        public int StoreId { get; set; }
        public DateTime? LastPickupDate { get; set; }
    }
}

PullListManager/Controllers/PullListController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PullListManager.Data;
using PullListManager.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PullListManager.Controllers
{
    public class PullListController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public PullListController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        // GET: PullList/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);

            var pullList = await _context.PullLists
                .SingleOrDefaultAsync(m => m.Id == id);

            if (pullList == null)
            {
                return NotFound();
            }

            pullList.Books = await _context.ComicBooks.Where(b => b.PullListId == pullList.Id).ToListAsync();

            if(currentUser.RoleName == "Owner" && currentUser.StoreId != pullList.StoreId)
            {
                // Show "Not Authorized" page
                return RedirectToAction("NotAllowed", "Home");
            }

            return View(pullList);
        }

        //POST: PullList/Details/5
        [HttpPost]
        public async Task<IActionResult> Details(int? id, string[] comicIds)
        {
            foreach(var comicId in comicIds)
            {
                _context.ComicBooks.Remove(await _context.ComicBooks.FindAsync(Guid.Parse(comicId)));
            }
            var pullList = await _context.PullLists.FindAsync(id);
            pullList.LastPickupDate = DateTime.Now;

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "PullList", id);
        }

        // GET: PullList/Create
        public IActionResult Create(int? storeId)
        {
            return View();
        }

        // POST: PullList/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("CustomerName,CustomerPhone,CustomerEmail,DepositAmount")] PullList pullList)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser.RoleName == "Owner" && currentUser.StoreId != pullList.StoreId)
            {
                // Show "Not Authorized" page
                return RedirectToAction("NotAllowed", "Home");
            }

            if (ModelState.IsValid)
            {
                if(_context.PullLists.Any(p => p.CustomerEmail == pullList.CustomerEmail && p.StoreId == id))
                {
                    return View(pullList);
                }

                pullList.StoreId = id;
                pullList.IsActive = true;
                pullList.DateCreated = DateTime.Now;

                _context.Add(pullList);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Store", new { id = pullList.StoreId });
            }
            return View(pullList);
        }

        // Get: PullList/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser.RoleName == "Owner" && currentUser.StoreId != id)
            {
                // Show "Not Authorized" page
                return RedirectToAction("NotAllowed", "Home");
            }

            if (id == null)
            {
                return NotFound();
            }

            var pullList = await _context.PullLists.SingleOrDefaultAsync(p => p.Id == id);
            return View(pullList);
        }

        // POST: PullList/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int pullListid, [Bind("Id,CustomerName,CustomerPHone,CustomerEmail,DepositAmount")] PullList pullList)
        {
            if(pullListid != pullList.Id)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            //{
            //    try
            //    {
            //        _context.Update(pullList);
            //        await _context.SaveChangesAsync();
            //    }
            //    catch (DbUpdateConcurrencyException)
            //    {
            //        if (!_context.PullLists.Any(p => p.Id == id))
            //        {
            //            return NotFound();
            //        }
            //        else
            //        {
            //            throw;
            //        }
            //    }
            //    return RedirectToAction("Details", id);
            //}
            //return View(pullList);
            return RedirectToAction("Details", "PullList", new { id = pullListid });
        }
    }
}

PullListManager/Controllers/PullListRequestController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PullListManager.Data;
using PullListManager.Models;
using System.Threading.Tasks;

namespace PullListManager.Controllers
{
    public class PullListRequestController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public PullListRequestController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [ActionName("_CreatePullListRequest")]
        public async Task<IActionResult> CreateAsync(int pullListId)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var currentPullList = await _context.PullLists.FindAsync(pullListId);
            if (currentUser.RoleName == "Owner" && currentUser.StoreId != currentPullList.StoreId)
            {
                // Show "Not Authorized" page
                return RedirectToAction("NotAllowed", "Home");
            }
            return View();
        }

        [ActionName("_CreatePullListRequest")]
        [HttpPost]
        public async Task<IActionResult> Create(int id, [Bind("RequestTitle")] PullListRequest pullListRequest)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var currentPullList = await _context.PullLists.FindAsync(id);
            if (currentUser.RoleName == "Owner" && currentUser.StoreId != currentPullList.StoreId)
            {
                // Show "Not Authorized" page
                return RedirectToAction("NotAllowed", "Home");
                
            }

            pullListRequest.PullListId = id;

            _context.Add(pullListRequest);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "PullList", new { id = pullListRequest.PullListId });
        }

        public async Task<IActionResult> Delete(int id)
        {
            var pullListRequest = await _context.PullListRequests.FindAsync(id);
            _context.PullListRequests.Remove(pullListRequest);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "PullList", new { id = pullListRequest.PullListId });
        }
    }
}

PullListManager/ViewComponents/PullListRequestsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PullListManager.Data;
using PullListManager.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PullListManager.ViewComponents
{
    public class PullListRequestsViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _dbContext;

        public PullListRequestsViewComponent(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IViewComponentResult> InvokeAsync(int pullListId)
        {
            var pullListRequests = await GetPullListRequestsAsync(pullListId);
            return View(pullListRequests);
        }

        private Task<List<PullListRequest>> GetPullListRequestsAsync(int pullListId)
        {
            return _dbContext.PullListRequests.Where(plr => plr.PullListId == pullListId).OrderBy(plr => plr.RequestTitle).ToListAsync();
        }
    }
}

PullListManager/Views/PullList/Create.cshtml
@model PullList

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

    <h4>Pull List</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <input type="hidden" asp-for="StoreId" />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="CustomerName" class="control-label"></label>
                    <input asp-for="CustomerName" class="form-control" />
                    <span asp-validation-for="CustomerName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CustomerPhone" class="control-label"></label>
                    <input asp-for="CustomerPhone" class="form-control" />
                    <span asp-validation-for="CustomerPhone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CustomerEmail" class="control-label"></label>
                    <input asp-for="CustomerEmail" class="form-control" />
                    <span asp-validation-for="CustomerEmail" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DepositAmount" class="control-label"></label>
                    <input asp-for="DepositAmount" class="form-control" />
                    <span asp-validation-for="DepositAmount" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a href='javascript:history.go(-1)'>Back</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>
</html>

PullListManager/Views/PullList/Details.cshtml
@model PullListManager.Models.PullList

<h2>Pull List Details</h2>
<hr />
<h3>Name: @Model.CustomerName</h3>
<h3>Last Pickup Date: @Model.LastPickupDate?.ToString("MM/dd/yy")</h3>

<h3>Date Created: @Model.DateCreated.ToString("MM/dd/yy")</h3>
<hr />
<a asp-action="Edit" asp-route-id="@Model.Id">Edit Pull List</a><span> | </span><a href='javascript:history.go(-1)'>Back</a>
<hr />
<div class="detail-tabs">
    <ul class="nav nav-tabs" id="pull-list-comics-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link" id="selected-tab" data-toggle="tab" href="#selected" role="tab" aria-controls="selected" aria-selected="false">Selected <span class="badge badge-light">@Model.Books?.Where(b => b.BookStatus == BookStatus.SELECTED).Count()</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="ordered-tab" data-toggle="tab" href="#ordered" role="tab" aria-controls="ordered" aria-selected="false">Ordered <span class="badge badge-light">@Model.Books?.Where(b => b.BookStatus == BookStatus.ORDERED).Count()</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" id="instore-tab" data-toggle="tab" href="#instore" role="tab" aria-controls="instore" aria-selected="true">In Store <span class="badge badge-light">@Model.Books?.Where(b => b.BookStatus == BookStatus.IN_STORE).Count()</span></a>
        </li>
    </ul>
    <div class="tab-content" id="pull-list-comics-tab-content">
        <div class="tab-pane fade" id="selected" role="tabpanel" aria-labelledby="selected-tab">
            <table class="table">
                <thead>
                    <tr>
                        <th>Order Number</th>
                        <th>Title</th>
                        <th>Expected Delivery Date</th>
                    </tr>
                </thead>
                <tbody class="list-group">
                    @foreach (var comic in Model.Books.Where(c => c.BookStatus == BookStatus.SELECTED).OrderBy(c => c.Title))
                    {
                        <tr>
                            <td>@comic.OrderNumber</td>
                            <td><a href="@comic.PreviewsLink">@comic.Title</a></td>
                            <td>@comic.DeliveryDate?.ToString("MM/dd/yy")</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="tab-pane fade" id="ordered" role="tabpanel" aria-labelledby="profile-tab">
            <table class="table">
                <thead>
                    <tr>
                        <th>Order Number</th>
                        <th>Title</th>
                        <th>Expected Delivery Date</th>
                    </tr>
                </thead>
                <tbody class="list-group">
                    @foreach (var comic in Model.Books.Where(c => c.BookStatus == BookStatus.ORDERED).OrderBy(c => c.Title))
                    {
                        <tr>
                            <td>@comic.OrderNumber</td>
                            <td><a href="@comic.PreviewsLink">@comic.Title</a></td>
                            <td>@comic.DeliveryDate?.ToString("MM/dd/yy")</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="tab-pane fade active in" id="instore" role="tabpanel" aria-labelledby="contact-tab">
            <form asp-action="Details">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Pickup</th>
                            <th>Order Number</th>
                            <th>Title</th>
                            <th>Expected Delivery Date</th>
                        </tr>
                    </thead>
                    <tbody class="list-group">
                        @foreach (var comic in Model.Books.Where(c => c.BookStatus == BookStatus.IN_STORE).OrderBy(c => c.Title))
            {
                <tr>
                    <td><input name="comicIds" value="@comic.Id" type="checkbox" /></td>
                    <td>@comic.OrderNumber</td>
                    <td><a href="@comic.PreviewsLink">@comic.Title</a></td>
                    <td>@comic.DeliveryDate?.ToString("MM/dd/yy")</td>
                </tr>
}
                    </tbody>
                </table>
                <div class="form-group">
                    <input type="submit" value="Pickup Comics" class="btn btn-default" />
                </div>
            </form>

        </div>
    </div>
</div>
<div class="detail-pull-list-requests">
    <h2>Pull List Requests</h2>
    @await Html.PartialAsync("_CreatePullListRequest", new PullListRequest())
    @await Component.InvokeAsync("PullListRequests", new { pullListId = Model.Id })
</div>

PullListManager/Views/PullList/Edit.cshtml
@model PullList


<h4>Edit Pull List</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="PullList" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhone" class="control-label"></label>
                <input asp-for="CustomerPhone" class="form-control" />
                <span asp-validation-for="CustomerPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerEmail" class="control-label"></label>
                <input asp-for="CustomerEmail" class="form-control" />
                <span asp-validation-for="CustomerEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepositAmount" class="control-label"></label>
                <input asp-for="DepositAmount" class="form-control" />
                <span asp-validation-for="DepositAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PullListManager/Views/PullList/_CreatePullListRequest.cshtml
@model PullListRequest

<div class="col-md-3">
    <form asp-controller="PullListRequest" asp-action="_CreatePullListRequest">
        <input type="hidden" asp-for="Id" />
        <input asp-for="RequestTitle" class="form-control"> <input type="submit" value="Add Pull List Request" class="btn btn-default" />
    </form>
</div>